import { Barlow } from "next/font/google";
import localFont from "next/font/local";
import Navbar from "@/components/wrapper/navbar";
import "./globals.css";
import { Footer } from "@/components/wrapper/footer";

const barlow = Barlow({
  subsets: ["latin"],
  weight: ["400", "700"], // Specify the weights you need
  variable: "--font-primary",
});

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type RootLayoutProps = {
  children: React.ReactNode;
};

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body
        className={`${barlow.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
